/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/app/AppFooter.vue')['default']
    AppLogo: typeof import('./components/app/AppLogo.vue')['default']
    Channels: typeof import('./components/channels/Channels.vue')['default']
    ChannelsContent: typeof import('./components/channels/ChannelsContent.vue')['default']
    ChannelsItem: typeof import('./components/channels/ChannelsItem.vue')['default']
    ChannelsList: typeof import('./components/channels/ChannelsList.vue')['default']
    ChannelsNav: typeof import('./components/channels/ChannelsNav.vue')['default']
    ChatIList: typeof import('./components/chats/ChatIList.vue')['default']
    ChatIsList: typeof import('./components/chats/ChatIsList.vue')['default']
    ChatItem: typeof import('./components/chats/ChatItem.vue')['default']
    Chats: typeof import('./components/chats/Chats.vue')['default']
    ChatsContent: typeof import('./components/chats/ChatsContent.vue')['default']
    ChatsDefault: typeof import('./components/chats/ChatsContent.vue')['default']
    ChatsIList: typeof import('./components/chats/ChatsIList.vue')['default']
    ChatsItem: typeof import('./components/chats/ChatsItem.vue')['default']
    ChatsList: typeof import('./components/chats/ChatsList.vue')['default']
    ChatsNav: typeof import('./components/chats/ChatsNav.vue')['default']
    Communities: typeof import('./components/communities/Communities.vue')['default']
    CommunitiesContent: typeof import('./components/communities/CommunitiesContent.vue')['default']
    CommunitiesNav: typeof import('./components/communities/CommunitiesNav.vue')['default']
    Footter: typeof import('./components/app/AppFooter.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    IconAd: typeof import('./components/icons/IconAd.vue')['default']
    IconAD: typeof import('./components/icons/IconAD.vue')['default']
    IconCatalog: typeof import('./components/icons/IconCatalog.vue')['default']
    IconChannels: typeof import('./components/icons/IconChannels.vue')['default']
    IconChats: typeof import('./components/icons/IconChats.vue')['default']
    IconCommunities: typeof import('./components/icons/IconCommunities.vue')['default']
    IconHellp: typeof import('./components/icons/IconHelp.vue')['default']
    IconHelp: typeof import('./components/icons/IconHelp.vue')['default']
    IconLabel: typeof import('./components/icons/IconLabel.vue')['default']
    IconMen: typeof import('./components/icons/IconMen.vue')['default']
    IconNewChat: typeof import('./components/icons/IconNewChat.vue')['default']
    IconPlus: typeof import('./components/icons/IconPlus.vue')['default']
    IconQuick: typeof import('./components/icons/IconQuick.vue')['default']
    IconStatus: typeof import('./components/icons/IconStatus.vue')['default']
    IconTools: typeof import('./components/icons/IconTools.vue')['default']
    Logo: typeof import('./components/app/AppLogo.vue')['default']
    NewChat: typeof import('./components/icons/NewChat.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Status: typeof import('./components/status/Status.vue')['default']
    StatusContent: typeof import('./components/status/StatusContent.vue')['default']
    StatusItem: typeof import('./components/status/StatusItem.vue')['default']
    StatusList: typeof import('./components/status/StatusList.vue')['default']
    StatusNav: typeof import('./components/status/StatusNav.vue')['default']
    Text: typeof import('./components/app/Text.vue')['default']
    TextWithEmoji: typeof import('./components/app/TextWithEmoji.vue')['default']
    Tools: typeof import('./components/tools/Tools.vue')['default']
    ToolsContent: typeof import('./components/tools/ToolsContent.vue')['default']
    ToolsNav: typeof import('./components/tools/ToolsNav.vue')['default']
  }
}
